### ISSUE TITLE
Do not log the secret

### ISSUE THREAD

**Issue by Tristan971** [DevBlocky/scalpel#42]
Should avoid ever logging the user's secret -- causes trouble for debugging and makes it harder to get client run logs in benchmarks :/

**Comment by DevBlocky** [comment]
Client secrets should now be hidden in `Config` and `PingRequest` structs so no more worries about that. Out of curiosity, do you think `token_key` fields from the server also be hidden?

**Comment by Tristan971** [comment]
the token key is fine since it's transient 👍
