### ISSUE TITLE
Cipher chosen by server instead by client

### ISSUE THREAD

**Issue by 27136773** [DevBlocky/scalpel#47]
Instead of using a TLS configuration that let the HTTPS client select the cipher (see [mozilla_intermediate](https://github.com/DevBlocky/scalpel/blob/bf0302ff1d433e6a0e82987d7854e70ec4d38a07/src/http/mod.rs#L310)), use a TLS configuration that let the server choose a cipher with an algorithm optimized for the underlying hardware to improve performance.

In [benchmarks](https://gitlab.com/mangadex-network/client-benchmark/-/blob/main/README.md) it was observed that the performance could be improved by ~10% after forcing `apache-bench` to use `AES-256-GCM` instead of the automatic selected `ChaCha20-Poly1305`.

**Comment by DevBlocky** [comment]
You've probably already guessed, but I'm kina unfamiliar with SSL/TLS. I have more of a set-it and forget-it mentality when it comes to dealing with it.

I've implemented a change that allows clients to customize their TLS1 and TLS1.3 ciphersuites through the configuration. In addition, the defaults should hopefully be much better (no more `ChaCha20-Poly1305`!)

**Comment by 27136773** [comment]
Looks nice, with the [recent change](https://github.com/DevBlocky/scalpel/blob/main/src/http/mod.rs#L348) apache-bench now automatically gets the fastest server side cipher.
With this and probably the other recent adjustments, [scalpel is now heads on with mdathx](https://gitlab.com/mangadex-network/client-benchmark/-/blob/main/README.md) (at least regarding SSL performance).
